# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ main ]

jobs:
#First we will see the application build or not , then we will deploy in EC2
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

  Deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PK_QA  }}
            HOSTNAME : ${{ secrets.AWS_QA  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
            #Now we have got the access of EC2 and we will start the deploy .
            cd /home/ubuntu/bhtestt &&
            git checkout main &&
            git fetch --all &&
            git reset --hard origin/main &&
            git pull origin main &&
            cat <<'EOF' >.env.qa
              SECRETE_KEY = THISisMYSecnywherewithoutanytension
              
              #Core
              APP_URL = https://qa.yesspark.io
              BASE_URL = https://qa.yesspark.io/api/v2
              PORT = 4040
              DB_URL=${{ secrets.DB_URL }}
              
              #AWS SES
              EMAIL_SERVER=AmazonSesSmtp
              SMTP_AMZN_USER=AK
              SMTP_AMZN_PASS=BFaWyL2MAoVybH211DiVFRRmq3x
              VARIFIED_AWS_EMAIL = '"YesSpark" \<account-noreply@yesspark.io\>'
              
              #AWS S3
              AWS_ACCESS_KEY_ID="AKIAJFLDTQ"
              AWS_ACCESS_KEY_SECRET="v8TSSO8hwyecj8Em6Ec"
              AWS_S3_BUCKET_NAME="thesparkone"
              AWS_S3_ACL="public-read"
              AWS_S3_PUBLIC_URL="https://thesparkone.s3.us-west-2.amazonaws.com"
              
              #RabbitMQ
              RABBITMQ_URL="amqp://sparkland_user:c!VexePHobes@ec2-34-208-165-241.us-west-2.compute.amazonaws.com/sparkland_test"
              LOCAL_RABBITMQ_URL=amqp://admin:admin@localhost:5672
              
              ##### Not Use Anymore ######
              #ChargeBee
              CHARGEBEE_BASEURL = https://sparkland-test.chargebee.com/api/v2
              CHARGEBEE_BUSINESS_ENTITY_ID = __dev__8at09TEfAyAk2
              CHARGEBEE_SITE = "sparkland-test"
              CHARGEBEE_API_KEY= "test_hWs9TRZE5dc8r6o"
              
              ##### Not Use Anymore ######
              LOCAL_BASE_URL = http://localhost:4040/api/v2
              SMTP_USER = AKIAWLLCISWV
              SMTP_PASS = f2nYL5kqZC
              localhost ="localhost"
              ROCKSET_APIKEY = XbdHggR6grFthCU25GRyDJW3JpfXbqzAfpNdIldDs6b
          EOF
            echo "hello"
          '
